language: CSharp
mono:
 - latest
install:
- npm install -g bower
- curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
- dnvm upgrade
script:
- dnu restore
- dnu build